### ISSUE TITLE
Setup Files

### ISSUE THREAD

**Issue by ddvs1** [calvintam236/miningcore-ui#1]
Hi,

we are trying your project, but we dono how to adapt to our pool, we only see one address in miningcore-ui.js but the dashboard still empty.
any help ?

Regards,

Luis

**Comment by calvintam236** [comment]
Hi Luis,

The UI is using hard coded data as the API is not ready for further UI implementation. It is not ready for use yet.

**Comment by ddvs1** [comment]
OK,

i go try do something with your code.
I let you know.

Regards,

Luis

**Comment by mario1987** [comment]
Are there ant pics of this UI ??

**Comment by calvintam236** [comment]
This UI is customized on a theme - [Paper Dashboard](https://www.creative-tim.com/product/paper-dashboard).

![screen shot 2017-12-12 at 12 16 40 pm](https://user-images.githubusercontent.com/6436149/33906304-6d222d62-df36-11e7-982b-40d60f2d11e4.png)
![screen shot 2017-12-12 at 12 16 54 pm](https://user-images.githubusercontent.com/6436149/33906306-6d639c66-df36-11e7-90d5-8218c5e8618a.png)
and more...

**Comment by mario1987** [comment]
Nice it looks good. Can you also implement the option to easily import other themes?  In a management page or something.

**Comment by calvintam236** [comment]
@mario1987 This UI coding is based on this theme. This UI runs on pure HTML, CSS and JavaScript (client side), you need to manual port the coding to another theme with modification. You're welcome to make a pull request for a new branch if you found an alternative theme.

**Comment by calvintam236** [comment]
I have added the basic setup instructions at README. I'm closing this issue.
