### ISSUE TITLE
Miners graph

### ISSUE THREAD

**Issue by pfeiflelukas** [calvintam236/miningcore-ui#10]
@calvintam236  This graph doesn't appear to work. I have tried to fix it but got no where. Is it because the api doesn't support the graph?

Thanks

**Comment by pfeiflelukas** [comment]
@calvintam236 Also just realised that the graphs are in hashes. Makes it hard when miners have MH/s

**Comment by calvintam236** [comment]
@pfeiflelukas Looks like `http://35.184.15.200:4000/api/` is offline. If you bring it back online, I can test it on my side.

**Comment by pfeiflelukas** [comment]
@calvintam236 i did just restart the server. http://35.184.15.200:4000/api/pools is now up and running

**Comment by calvintam236** [comment]
@pfeiflelukas I see `No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 404.` on the API.

Can you try [this workaround](https://github.com/coinfoundry/miningcore/issues/3#issuecomment-346104332)?

**Comment by pfeiflelukas** [comment]
@calvintam236 Are you trying to use that link above? i am unaware that there is an issue with the site. Does the front end appear correct with all the correct information in the stats page? I will give it ago

**Comment by calvintam236** [comment]
@pfeiflelukas Only the `/api/pools` has CORS header. The rest don't and result in 404 error. If you are running the latest `master`, maybe @oliverw can fix that?

**Comment by oliverw** [comment]
@calvintam236 I'm not sure how it would be possible that only one response has CORS headers given that the method responsible for sending all responses adds those headers: https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Api/ApiServer.cs#L114

**Comment by calvintam236** [comment]
@oliverw You can test it with `http://35.184.15.200:4000/api/pool/monacoin/stats/hourly`, which `/api/pools` works.

**Comment by calvintam236** [comment]
@oliverw I think I found where is the problem - the API endpoint can be reach is `/api/pools/<id>/XXX`, not `/api/pool/<id>/XXX` listed in the API page. Example: http://5.189.159.254:4000/api/pools/straks1/

Which way is the correct one?

**Comment by calvintam236** [comment]
Fixed it in last commit.
