### ISSUE TITLE
Any idea why NetworkDifficulty is a crazy number?

### ISSUE THREAD

**Issue by jmoeltjen** [calvintam236/miningcore-ui#13]
Network Diff is showing up as "6.570702248007084e+40 E" for example, when reported network diff by coin is 14281.24, for example.

Am I missing a conversion value or something here, or is the wrong number being reported to the API?

**Comment by calvintam236** [comment]
What Miningcore version are you running?

Can you dump the JSON output on your server `/api/pools`?

**Comment by jmoeltjen** [comment]
We pulled master and built on Saturday (so current, but not straight from the release). API is offline right now, but the networkDifficulty for ZCL was reporting as: `"networkDifficulty": 5.8274765638035411E+58,` - will try to get you a full dump of the /api/pools json when it's back online.

**Comment by jmoeltjen** [comment]
Here's a json dump
`{
  "pools": [
    {
      "id": "Zen",
      "coin": {
        "type": "ZEN",
        "algorithm": "Equihash"
      },
      "ports": {
        "5050": {
          "listenAddress": "0.0.0.0",
          "difficulty": 0.5,
          "varDiff": {
            "minDiff": 0.01,
            "maxDiff": 2.0,
            "maxDelta": 1.0,
            "targetTime": 10.0,
            "retargetTime": 40.0,
            "variancePercent": 30.0
          }
        },
        "5051": {
          "listenAddress": "0.0.0.0",
          "difficulty": 5.0,
          "varDiff": {
            "minDiff": 0.01,
            "maxDiff": 15.0,
            "maxDelta": 1.0,
            "targetTime": 15.0,
            "retargetTime": 60.0,
            "variancePercent": 30.0
          }
        }
      },
      "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 0.01,
        "payoutScheme": "PPLNS",
        "payoutSchemeConfig": {
          "factor": 2.0
        }
      },
      "clientConnectionTimeout": 600,
      "jobRebroadcastTimeout": 10,
      "blockRefreshInterval": 5,
      "poolFeePercent": 1.0,
      "address": "znXNKnKHvecC9mKPaSLgjWXwZFnYsbokCa9",
      "addressInfoLink": "http://explorer.zensystem.io/accounts/znXNKnKHvecC9mKPaSLgjWXwZFnYsbokCa9",
      "poolStats": {
        "connectedMiners": 1,
        "poolHashRate": 83,
        "validSharesPerSecond": 0
      },
      "networkStats": {
        "networkHashRate": 40922082.0,
        "networkDifficulty": 6.7099090966673021E+58,
        "lastNetworkBlockTime": "2018-02-13T15:33:56.68628",
        "blockHeight": 256738,
        "connectedPeers": 8
      },
      "topMiners": [],
      "totalPaid": 0.0
    },
    {
      "id": "Zel",
      "coin": {
        "type": "ZEL",
        "algorithm": "Equihash"
      },
      "ports": {
        "5052": {
          "listenAddress": "0.0.0.0",
          "difficulty": 0.5,
          "varDiff": {
            "minDiff": 0.01,
            "maxDiff": 2.0,
            "maxDelta": 1.0,
            "targetTime": 10.0,
            "retargetTime": 30.0,
            "variancePercent": 30.0
          }
        },
        "5053": {
          "listenAddress": "0.0.0.0",
          "difficulty": 5.0,
          "varDiff": {
            "minDiff": 0.1,
            "maxDiff": 15.0,
            "maxDelta": 1.0,
            "targetTime": 15.0,
            "retargetTime": 60.0,
            "variancePercent": 30.0
          }
        }
      },
      "paymentProcessing": {
        "enabled": true,
        "minimumPayment": 0.01,
        "payoutScheme": "PPLNS",
        "payoutSchemeConfig": {
          "factor": 2.0
        }
      },
      "clientConnectionTimeout": 600,
      "jobRebroadcastTimeout": 10,
      "blockRefreshInterval": 5,
      "poolFeePercent": 0.5,
      "address": "t1R2XbJ9qyrhadGJRRqwcJUYD9aaAY65ppD",
      "addressInfoLink": "http://explorer.zel.cash/address/t1R2XbJ9qyrhadGJRRqwcJUYD9aaAY65ppD",
      "poolStats": {
        "connectedMiners": 1,
        "poolHashRate": 1503,
        "validSharesPerSecond": 0
      },
      "networkStats": {
        "networkHashRate": 1449060.0,
        "networkDifficulty": 7.4131668605396861E+58,
        "lastNetworkBlockTime": "2018-02-13T15:31:06.004804",
        "blockHeight": 11281,
        "connectedPeers": 8
      },
      "topMiners": [
        {
          "miner": "t1Q16bFZ9kn3VKfdhUJHuBiveFfPrWrQy6z",
          "hashrate": 1905.769226913942,
          "sharesPerSecond": 0.12376106764074263
        },
        {
          "miner": "t1MZ4pBVuSXxAtbYW72AjsAcqQyt74Au5Az",
          "hashrate": 99.854114577183211,
          "sharesPerSecond": 0.11876777834455846
        }
      ],
      "totalPaid": 0.0
    }
  ]
}`

**Comment by jmoeltjen** [comment]
Any ideas @calvintam236 ? I appreciate it.

**Comment by calvintam236** [comment]
@jmoeltjen The network difficulty reported back from API does not match the value I see on other pools.

Can you confirm any problem with the reported network difficulty on ZEN, @oliverw?

**Comment by calvintam236** [comment]
Fixed in miningcore `dev` branch.
