### ISSUE TITLE
Data collect error result in NaN display (empty charts as well)

### ISSUE THREAD

**Issue by ffrouin** [calvintam236/miningcore-ui#14]
Hello,

I found small issues in miningcore-ui.js, just need to rename some var (caps R need to become r in hashrate word) :

value.poolStats.poolHashRate into value.poolStats.poolHashrate
value.networkStats.networkHashRate into value.networkStats.networkHashrate
value.networkHashRate into value.networkHashrate
value.hashRate into value.hashrate
value2.hashRate into value2.hashrate

Freddy.

**Comment by bitspill** [comment]
Could you create a pull request with those corrections?

**Comment by ffrouin** [comment]
Done.
