### ISSUE TITLE
Error: No response from API. (loadPools)

### ISSUE THREAD

**Issue by dangerm0us** [calvintam236/miningcore-ui#16]
Getting this from the UI, even though the pool is running and API is up on 127.0.0.1:4000

Content served via nginx.

Any ideas?  

Thanks.

**Comment by calvintam236** [comment]
```javascript
var API = ''; // API address
```
What is the value you set?

**Comment by dangerm0us** [comment]
var API = 'http://127.0.0.1:4000/api/'; // API address

**Comment by calvintam236** [comment]
Can you see what message is logged on the console (browser developer tool)?

**Comment by dangerm0us** [comment]
`Failed to load resource: net::ERR_CONNECTION_REFUSED`

I've possibly got a config issue with nginx I'd say.

**Comment by dangerm0us** [comment]
Is the port 4000 supposed to be available to the internet?

**Comment by calvintam236** [comment]
you need to set the port accessible to Internet if you are letting other miners to access it.

**Comment by dangerm0us** [comment]
Right, I had assumed (incorrectly) that it would be a server side call to get the stats from the pool API over to the UI.  I don't have port 4000 open to the internet, that must be my problem.  Thanks!

**Comment by calvintam236** [comment]
Please reopen if you couldn't fix it after opening port 4000 to Internet.
