### ISSUE TITLE
Error: No response from API. (loadPools)

### ISSUE THREAD

**Issue by dmshel** [calvintam236/miningcore-ui#17]
port 4000 is open
```javascript
// config
var API = 'https://127.0.0.1:4000/api/'; // API address
var defaultPool = 'zec1'; // Default Pool ID

var currentPool = defaultPool;
```

API is online
```console
$ wget -O - http://127.0.0.1:4000/api/pools/zec1
--2018-03-15 05:21:18--  http://127.0.0.1:4000/api/pools/zec1
Connecting to 127.0.0.1:4000... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: ‘STDOUT’
```

But at web i see Error: No response from API. (loadPools)

![default](https://user-images.githubusercontent.com/37098267/37443716-5d5e7be4-2840-11e8-9290-67496632a380.JPG)

**Comment by calvintam236** [comment]
What is your API settings in `config.json`? By the look at the error, miningcore is refusing to connect. Is `"listenAddress": "0.0.0.0",`?

**Comment by dmshel** [comment]
@calvintam236 
![default](https://user-images.githubusercontent.com/37098267/37444487-6d1ef4b0-2844-11e8-95f4-60b2453f2029.JPG)

**Comment by calvintam236** [comment]
Are you running miningcore in docker or separate machine than what you are testing on. Please go to http://127.0.0.1:4000/api/pools on your browser, and see is if the connection refused as well.

**Comment by dmshel** [comment]
ERR_CONNECTION_TIMED_OUT
separate machine

**Comment by calvintam236** [comment]
Clearly, you don't know what is 127.0.0.1 or localhost. You cannot use 127.0.0.1 in separate machine. Please google it.
Use server IP instead and try again.
