### ISSUE TITLE
Drop down menu for coins #5 again help

### ISSUE THREAD

**Issue by dmshel** [calvintam236/miningcore-ui#18]
Hello
I have a error
Drop down menu for coins #5
I try use this  Fix #5 but still have eror
How 2 fix this?

**Comment by calvintam236** [comment]
Please attach the error. No idea what is the problem.

**Comment by dmshel** [comment]
I choose BTG. I switch to a friend tab, and the coin is reset to ZEC. After updating the page, I always see ZEC.
![default](https://user-images.githubusercontent.com/37098267/37551303-fff5f5ae-29cf-11e8-8076-1c3a2da7df98.JPG)

**Comment by calvintam236** [comment]
As stated here, pool selection is not stored. You're welcome send me a PR. https://github.com/calvintam236/miningcore-ui/issues/5#issuecomment-348310635
