### ISSUE TITLE
statistic error 

### ISSUE THREAD

**Issue by itsmylife44** [calvintam236/miningcore-ui#19]
Hey , all right done with miningcore , and it's running :D 

but on ste page  , the statistic is 

Network's Hash Rate
0 H/s

but in 

Network Difficulty
3.23494 P

 it's updated .. 
where is the issue ? 

thank you

**Comment by calvintam236** [comment]
Please attach the json output at `/api/pools/`.

**Comment by itsmylife44** [comment]
uhm .. 404 Not Found

**Comment by calvintam236** [comment]
Your JSON output suggested that `networkHashrate` is `0`. Nothing wrong at the UI. Please report this bug at miningcore.
