### ISSUE TITLE
Y Axis on Graphs

### ISSUE THREAD

**Issue by pfeiflelukas** [calvintam236/miningcore-ui#21]
Hi all,

The Y axis on the graphs is represented in Hashes per second. I have tried to change this and represent it as either MH/s or GH/s depending on the pools hashing speed but i have gotten nowhere so far. Does anyone know how to accomplish this?

Thanks

**Comment by calvintam236** [comment]
Look at [here](https://github.com/calvintam236/miningcore-ui/blob/develop/assets/js/miningcore-ui.js#L136). Replace `_formatter()` call here.

**Comment by calvintam236** [comment]
I'm closing this. Let me know if you have other question.

**Comment by pfeiflelukas** [comment]
@calvintam236 Every time i use the formatter() i get the same error. "_formatter is not defined".

**Comment by calvintam236** [comment]
@pfeiflelukas Where are you calling it? It's at [here](https://github.com/calvintam236/miningcore-ui/blob/develop/assets/js/miningcore-ui.js#L8).

**Comment by pfeiflelukas** [comment]
@calvintam236 Legend, i had my function setup incorrectly.
