### ISSUE TITLE
API Issue 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by pfeiflelukas** [calvintam236/miningcore-ui#3]
Hi all,

Just ran some more tests trying to get this working with miningcore. The API is working well and i can access via postman and via chrome. However i keep getting this error message which stops the parsing of the JSON object.

Failed to load http://x:4000/api/pools: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://x' is therefore not allowed access 

Does anyone know this issue?

Thanks

**Comment by calvintam236** [comment]
Unless you run on the same domain as your server, you will get this error. I'm waiting @oliverw to fix that too..

**Comment by oliverw** [comment]
I'll fix it but please do not open the API to the internet on production servers. Simply don't.

**Comment by oliverw** [comment]
Fixed by https://github.com/coinfoundry/miningcore/commit/4406d5a9ffea7919dcbb231c022d68030e225186

**Comment by pfeiflelukas** [comment]
That worked perfectly. Thanks
