### ISSUE TITLE
Statistics page

### ISSUE THREAD

**Issue by pfeiflelukas** [calvintam236/miningcore-ui#4]
@calvintam236 I think quite a bit of important information is being missed here. Under the pool config it reads
 - Payout scheme
 - Minimum Payment w/o #
 - Minimum Payment w/ #
 - Pool Fee
 - Donation

Would it not be better to show:
 - Payout scheme
 - Minimum payment
 - Donation address taken from the pool admins nominated address in the config file
 - Pool Fee
 - Pool IP/host:Port

What do you think?

**Comment by calvintam236** [comment]
After a review on the [example API response](https://github.com/coinfoundry/miningcore/wiki/API), it does not provide wallet address for admin. You're welcome to hardcode that in the UI yourself on your copy.

I am going to add pool address & ports on the "Connect" page, as API provides a lot of info that I don't think it fits in the stats page.

**Comment by pfeiflelukas** [comment]
Ok no worries.

That makes sense as well i was just wary that it hasn't been included yet. 

I did also notice that button to select the coin in the drop down menu only works once, after which seems to do nothing.

**Comment by calvintam236** [comment]
I have added pool address to stats page at 1cc1729. The pool info card will be moved to connect page soon.

**Comment by calvintam236** [comment]
@pfeiflelukas I have moved the pool info card to the new connect page. 👍

**Comment by pfeiflelukas** [comment]
@calvintam236 Awesome work. I will take a look at the progress

**Comment by pfeiflelukas** [comment]
@calvintam236 what is the difference between the two minimum payments?

$('#minimumPayment1').text(value.paymentProcessing.minimumPayment + ' ' + value.coin.type);
$('#minimumPayment2').text(value.paymentProcessing.minimumPaymentToPaymentId + ' ' + value.coin.type);

**Comment by calvintam236** [comment]
By MiningCore config, the different is paying to a wallet with and without payment ID. For example, when you send to a exchange wallet, it requires you to have payment ID.
