### ISSUE TITLE
Drop down menu for coins

### ISSUE THREAD

**Issue by pfeiflelukas** [calvintam236/miningcore-ui#5]
@calvintam236 I have searched and tried to fix this problem but haven't gotten anywhere yet. The drop down menu which allows you to select the pool only works once, then does nothing after. Can this be easily solved? If so how?

I think this the issue:
```html
<a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" id="currentPool"></a>
```

Would currentPool always be the same after the first switch?

Thanks

**Comment by calvintam236** [comment]
Which page you are referring to?

I haven't implement to save `currentPool` in the cookie, so once you left to another page, you will reset back to `defaultPool`. It is not difficult to do so, I just have no time yet. You are welcome to submit a pull request.

**Comment by pfeiflelukas** [comment]
![24257561_10214116115077706_1747424334_n](https://user-images.githubusercontent.com/20794390/33487602-b23c97f8-d6e8-11e7-8326-a97f27520415.png)

This is the drop which i mean. It only works once until the page is refreshed.

**Comment by pfeiflelukas** [comment]
<script type="text/javascript">
    $(document).ready(function() {
        loadPools()
            .always(function() { //debug,should be done()
                function render() {
                    setInterval(function load() {
                        loadStatsData();
                        return load;
                    }(), 10000);
                    setInterval(function load() {
                        loadStatsChart();
                        return load;
                    }(), 600000);
                }

                render();
                //must fix
                //bad practice also with the javascript void(0)
                $('#poolList li a').on('click', function(event) {
                    currentPool = $(event.target).attr('data-id');
                    loadPools();
                    render();
                });
            });
    });
</script>

This is the code which is only being called once. As far as i can tell.

**Comment by calvintam236** [comment]
As stated here, pool selection is not stored. You're welcome send me a PR. https://github.com/calvintam236/miningcore-ui/issues/5#issuecomment-348310635

**Comment by whody** [comment]
Calvin,

Have you made any progress with the drop down menu on the UI with multiple coins? It doesn't appear to work at all on responsive/mobile pages as well. Any quick tips for a noob to get started fixing the issue?

**Comment by calvintam236** [comment]
@whody What error message you are getting at developer console in the browser?
