### ISSUE TITLE
Input for miners address

### ISSUE THREAD

**Issue by pfeiflelukas** [calvintam236/miningcore-ui#7]
@calvintam236 I don't believe this is working at the moment. The webpage returns this when a user attempt to enter in their miner address.

- http://IP:4000/api/pool/coin/miner/*/stats

Where * should be the miners address. The API for miningcore does work and this is displayed properly. However miningcore-ui.js doesn't pick up the values. I made some changes so it will work but the input in dashboard.html doesn't send the new request when the user enter in their address. Should a button not be used to trigger this new call?

- $('#unconfirmedShares').text(data.pendingShares);
- $('#minerHashRate').text(data.hashrate); //was labelled wrong
- $('#unconfirmedBalance').text(data.pendingBalance);
- $('#lifetimeBalance').text(data.totalPaid); //was labelled wrong

This will get the correct details at least.

Thanks

**Comment by calvintam236** [comment]
For now, after you enter the address and left the field by clicking outside that input box, it will trigger the request. I guess I forgot to add timeout for the trigger after last change of the box.

**Comment by pfeiflelukas** [comment]
@calvintam236 I have attempted to trigger the request the way you mentioned but still no success. Any idea?

**Comment by calvintam236** [comment]
![demo](https://user-images.githubusercontent.com/6436149/33906435-c6530fbe-df36-11e7-9bfe-bdf49e0d0bd7.gif)
It works on my copy. Is this what you did?

**Comment by pfeiflelukas** [comment]
@calvintam236 I have now got it to work. But i first need to exit the input box then re-enter it to send the request. In the process of trying to get a button to trigger the response instead. But no luck so far, i dont really know where to start with this one.

**Comment by pfeiflelukas** [comment]
@calvintam236 Still no progress on that button, i just can't get the request to be send when the button is clicked. Do you have any ideas on how to do this?

**Comment by calvintam236** [comment]
https://github.com/calvintam236/miningcore-ui/blob/develop/dashboard.html#L437
This is the line you are looking for.

**Comment by pfeiflelukas** [comment]
Worked perfectly

Thanks

**Comment by calvintam236** [comment]
I have changed it to a button at 1cc1729.
