### ISSUE TITLE
License of use

### ISSUE THREAD

**Issue by pfeiflelukas** [calvintam236/miningcore-ui#8]
@calvintam236 Is this repo under an MIT license or something similar?

**Comment by calvintam236** [comment]
Fixed by 34c2aa1. Theme license is MIT, so I will stay with that.

**Comment by pfeiflelukas** [comment]
Thanks. Also do you have a BTC address for donations? Place it in the read me if you do please

**Comment by calvintam236** [comment]
@pfeiflelukas Yes, and I added the README (finally!) with the addresses on there 👍
