### ISSUE TITLE
Blocks page

### ISSUE THREAD

**Issue by pfeiflelukas** [calvintam236/miningcore-ui#9]
I just did a full scale test and the blocks page doesn't load previous blocks found when there are more than 1 coins implemented

**Comment by pfeiflelukas** [comment]
This script will fix it :) loadBlocksList(); was outside the onclick method
<script type="text/javascript">
    $(document).ready(function() {
        loadPools()
            .always(function() { //debug,should be done()
                $(document).on("click", "#poolList li a", function() {
                    currentPool = $(event.target).attr('data-id');
                    loadPools();
                    loadPaymentsList();
                    loadBlocksList();
                });
            });
    });
</script>

**Comment by calvintam236** [comment]
@pfeiflelukas Your UI is using the outdated base. Please pull from the current `develop` and merge into your code.

**Comment by pfeiflelukas** [comment]
@calvintam236 updated both and it is now working. thanks anyway
